### ISSUE TITLE
无法进入调试模式

### ISSUE THREAD

**Issue by RodJohn** [CHDQ/lombok-copy#1]
我在parser下面执行mvnDebug  ，并进入了监听状态
在idea中执行执行了remote的操作，
但是并不能进入调试模式

**Comment by CHDQ** [comment]
需要在usage中执行maven编译命令,附加-X参数,进入debugger

**Comment by CHDQ** [comment]
> 我在parser下面执行mvnDebug ，并进入了监听状态
> 在idea中执行执行了remote的操作，
> 但是并不能进入调试模式

需要在usage中debugger,通过mvn编译项目,用mvn的调试命令
> compile -X

在parser中对应位置打断点,就能进入debugger了
